import type { CollectionConfig } from 'payload'
import { checkRole } from '@/access/utilities'
import { shouldHideCollection } from '@/lib/tenant/shouldHideCollection'
import { autoGenerateSlugFromName } from '@/utilities/slugify'

/**
 * Destinations Collection — Toerisme Branch
 *
 * Bestemmingenbeheer voor reisbureaus en touroperators.
 * Bevat landen, continenten, klimaatinfo en reistips.
 */
export const Destinations: CollectionConfig = {
  slug: 'destinations',
  labels: {
    singular: 'Bestemming',
    plural: 'Bestemmingen',
  },
  admin: {
    group: 'Toerisme',
    useAsTitle: 'name',
    defaultColumns: ['name', 'country', 'continent', 'featured'],
    hidden: shouldHideCollection(),
  },
  access: {
    read: () => true,
    create: ({ req: { user } }) => checkRole(['admin', 'editor'], user),
    update: ({ req: { user } }) => checkRole(['admin', 'editor'], user),
    delete: ({ req: { user } }) => checkRole(['admin'], user),
  },
  versions: {
    drafts: true,
  },
  fields: [
    // ─── SIDEBAR ─────────────────────────────────────────────
    {
      name: 'featured',
      type: 'checkbox',
      label: 'Uitgelicht',
      defaultValue: false,
      admin: {
        position: 'sidebar',
      },
    },

    // ─── MAIN FIELDS ─────────────────────────────────────────
    {
      name: 'name',
      type: 'text',
      required: true,
      label: 'Naam',
      admin: {
        description: 'Bijv. "Bali", "Parijs", "Kenia"',
      },
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      label: 'Slug',
      hooks: {
        beforeValidate: [autoGenerateSlugFromName],
      },
      admin: {
        description: 'Automatisch gegenereerd uit de naam',
      },
    },
    {
      name: 'country',
      type: 'text',
      label: 'Land',
      admin: {
        description: 'Bijv. "Indonesië", "Frankrijk", "Kenia"',
      },
    },
    {
      name: 'continent',
      type: 'select',
      label: 'Continent',
      options: [
        { label: 'Europa', value: 'europa' },
        { label: 'Azië', value: 'azie' },
        { label: 'Afrika', value: 'afrika' },
        { label: 'Amerika', value: 'amerika' },
        { label: 'Oceanië', value: 'oceanie' },
      ],
    },
    {
      name: 'description',
      type: 'richText',
      label: 'Beschrijving',
    },
    {
      name: 'coverImage',
      type: 'upload',
      relationTo: 'media',
      label: 'Omslagafbeelding',
    },
    {
      name: 'icon',
      type: 'text',
      label: 'Icoon',
      admin: {
        description: 'Emoji icoon (bijv. 🏝️, 🗼, 🦁)',
      },
    },
    {
      name: 'climate',
      type: 'textarea',
      label: 'Klimaatinformatie',
      admin: {
        description: 'Korte beschrijving van het klimaat',
      },
    },
    {
      name: 'bestSeason',
      type: 'text',
      label: 'Beste reisperiode',
      admin: {
        description: 'Bijv. "April - Oktober", "Het hele jaar"',
      },
    },

    // SEO tab is auto-generated by seoPlugin (tabbedUI: true)
  ],
}
